In [1]:
import numpy as np

In [2]:
#Tao mang
a=np.array([1, 2, 3])

# In mang
print(a)

# In 1 phan tu
element = a[1]
print(element)

[1 2 3]
2


In [3]:
# Tao mang 2 chieu
matrix=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# In mang
print(matrix)

# In 1 phan tu
element = matrix[1, 2]
print(element)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6


In [4]:
#Tao mang toan so 0
a = np.zeros(5)
print(a)
#tao mang toan la 1
a= np.ones(6)
print(a)
# Tao mang rong
a=np.empty(6)
print(a)
# Tao mang tu 0-100
a=np.arange(100)
print(a)
# Tao mang gom cac thanh phan cach deu nhau
a=np.linspace(0, 20, num=5)
print(a)
#tao mang toan la 1
a= np.ones(6 ,dtype=np.int64)
a

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0.  5. 10. 15. 20.]


array([1, 1, 1, 1, 1, 1], dtype=int64)

In [5]:
#Tao mang
a=np.array([12, 55, 64, 4, 5])
print(a)
# Sap xep mang
a=np.sort(a)
print(a)
# Sap xep mang nguoc
a=np.sort(a)[::-1]
print(a)
# Them phan tu vao mang
a=np.append(a, 31)
print(a)
# Xoa 1 phan tu trong mang
a=np.delete(a, 2)
print(a)

[12 55 64  4  5]
[ 4  5 12 55 64]
[64 55 12  5  4]
[64 55 12  5  4 31]
[64 55  5  4 31]


In [18]:
# Tao mang 2 chieu
arr=np.array([[1, 2, 3], [5, 4, 6], [7, 8, 9]])

Sap_xep_theo_hang=np.sort(arr, axis=1) #tang dan
print(Sap_xep_theo_hang)

Sap_xep_theo_cot=np.sort(arr, axis=0) #tang dan
print(Sap_xep_theo_cot)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [5 4 6]
 [7 8 9]]


In [19]:
# Tao mang 2 chieu
arr=np.array([[1, 2, 3], [5, 4, 6], [7, 8, 9]])

Sap_xep_theo_hang=-np.sort(-arr, axis=1) #giam dan
print(Sap_xep_theo_hang)

Sap_xep_theo_cot=-np.sort(-arr, axis=0) #giam dan
print(Sap_xep_theo_cot)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [5 4 6]
 [1 2 3]]


In [26]:
# Tạo một mảng 2D
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sử dụng các thuộc tính để lấy thông tin về mảng
so_chieu = arr.ndim  # Số chiều (2 chiều)
kich_thuoc = arr.size  # Kích thước (tổng số phần tử, 6)
hinh_dang = arr.shape  # Hình dạng (số hàng x số cột, (2, 3))

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 6
Hình dạng: (2, 3)


In [27]:
#Chuyen doi kieu du lieu
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_float=arr.astype(float)
print(arr_float)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [31]:
#Thay doi hinh dang cua mang
a=np.array([12, 55, 64, 4, 5, 7])
reshaped_a=a.reshape(2,3)
print(reshaped_a)

[[12 55 64]
 [ 4  5  7]]


In [34]:
reshaped_a=reshaped_a.flatten() #chuyen thanh mang 1 chieu
print(reshaped_a)

[12 55 64  4  5  7]


In [36]:
# Cat lat mang
arr = np.array([1, 2, 3, 4, 5])

sub_arr = arr[1:4]  
print(sub_arr) 

sub_arr = arr[:-1]  
print(sub_arr)

sub_arr = arr[-2:]  
print(sub_arr)

[2 3 4]
[1 2 3 4]
[4 5]


In [37]:
# Chuyển vị mảng
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
# Để chuyển vị mảng, chúng ta có thể sử dụng .T hoặc hàm numpy.transpose().
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr=np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [50]:
arr = np.array([1, 2, 3, 4, 5])
total=np.sum(arr)
print("Tong gia tri cua mang la:", total)

average=np.mean(arr)
print("Gia tri trung binh cua mang la:", average)

min_value=np.min(arr)
max_value=np.max(arr)
print("Gia tri nho nhat cua mang la:", min_value)
print("Gia tri lon nhat cua mang la:", max_value)

std_deviation=np.std(arr)
print("Tinh do lech chuan cua mang:", std_deviation)

variance=np.var(arr)
print("phuong sai cua mang:", variance)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("Tong tich chap cua mang arr1 va arr2:", dot_product)

Tong gia tri cua mang la: 15
Gia tri trung binh cua mang la: 3.0
Gia tri nho nhat cua mang la: 1
Gia tri lon nhat cua mang la: 5
Tinh do lech chuan cua mang: 1.4142135623730951
phuong sai cua mang: 2.0
Tong tich chap cua mang arr1 va arr2: 32
